apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-evpm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-htdp-tenant/quarkus/devfile-sample-code-with-quarkus-evpm@sha256:79ae35bd80e92de02cc339d31359cd882e4ef4b8f23eedc64a4f280fa4c908f2
        name: my-java-quarkus
        resources: {}
status: {}
